### ISSUE TITLE
Can't find an installation instructions of your project.

### ISSUE THREAD

**Issue by NokKbl** [wisaTong/Freshwater#8]
Since I'm looking for the installation instructions of this project, I didn't see the instructions in both of your repositories ([Freshwater](https://github.com/wisaTong/Freshwater) and [Saltwater](https://github.com/wisaTong/Saltwater)).

- Could you please put the instructions in your README? **or** please let me know if you already have the installation instructions.

- I suggest that you should have a part in one of your README page for the installation instructions to make it easy to find then provide some descriptions and a link in another project repository to visit the README page that have the installation instructions. (Ps. It just my opinion)

**Comment by wisaTong** [comment]
Thank you for your feedback, we will be improving our README.md and include more clear installation instruction.

**Comment by NokKbl** [comment]
@wisaTong Thanks for your response.

Ps. I think it should be better and easier for other testers if you put commands to install the prerequisite software, so, they can just open your `README.md` and follow your instructions without open new window and search for those commands. Hope it helps!! 👍
